app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

contacts:
    type:     rest
    resource: AppBundle\Controller\ContactController

users:
    type:     rest
    resource: AppBundle\Controller\UserController

auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController